apiVersion: v1 
kind: Service 
metadata:
  name: service-production
  labels:
    tier: service-roduction
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32765
  selector:
    tier: Dev