apiVersion: v1 
kind: ReplicationController
metadata:
  name: first-replicationcontroller
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: nginx-label
        tier: db-production
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3

#it will create 3 pods of nginx in replication controller